---
- name: Add deadsnakes PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install Python3
  apt: pkg="{{ item }}" state=present
  with_items:
    - python3
    - python3-pip
    - python3-setuptools