---
- name: Install PostgreSQL
  apt: pkg="{{ item }}" state=present
  with_items:
    - postgresql
    - libpq-dev
    - postgresql-client
    - postgresql-client-common

- name: Add UbuntuGIS apt repository
  apt_repository:
    repo: ppa:ubuntugis/ppa

- name: Update APT cache
  apt: update_cache=yes

- name: Install PostGIS
  apt: pkg="{{ item }}" state=present
  with_items:
    - postgis
    - postgresql-10-postgis-2.4-scripts

- name: Install PostgreSQL driver for Python
  import_tasks: psycopg2.yml

- name: Create Toy database
  import_tasks: setup-db.yml