---
- name: Install PostgreSQL
  apt:
    state: present
    pkg:
      - postgresql
      - libpq-dev
      - postgresql-client
      - postgresql-client-common

- name: Add UbuntuGIS apt repository
  apt_repository:
    repo: ppa:ubuntugis/ppa

- name: Install PostGIS
  apt:
    state: present
    update_cache: yes
    pkg:
      - postgis
      - postgresql-10-postgis-2.4-scripts

- name: Install PostgreSQL driver for Python
  pip: name=psycopg2
       executable=/usr/bin/pip3
       version=2.8
       state=present

- name: Create Toy database
  import_tasks: setup-db.yml