---
- name: Make sure template_postgis exists
  postgresql_db: db=template_postgis state=present encoding=UTF-8 template=template0
  become_user: postgres
  register: createdb_template_postgis

- name: Spatially enable the template database
  command: psql -d template_postgis -c "CREATE EXTENSION IF NOT EXISTS postgis;"
  when: createdb_template_postgis.changed
  become_user: postgres

- name: Create postgres database
  postgresql_db: name="toy"
  become_user: postgres

- name: Create postgres user
  postgresql_user: db="toy"
                   name="admin"
                   password="fakepassword"
                   role_attr_flags=SUPERUSER
  become_user: postgres