---

# Installs packages/dependencies for web servers

- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.ruby", when: cicero_development }
    - { role: "azavea.nodejs", when: cicero_development }